### ISSUE TITLE
About reimplementing the model

### ISSUE THREAD

**Issue by avis-ma** [SheldonTsui/Minus-Plus-Network#1]
Hi,
    when I reimplement the model on my own dataset, I got an error.
   with parameter --binary_mask 1 and --loss bce.
   the error is 
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THCUNN/BCECriterion.cu:74: Acctype bce_functor_weights<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [44,0,0], thread: [251,0,0] Assertion `input >= 0. && input <= 1.` failed.
`RuntimeError: reduce failed to synchronize: cudaErrorAssert: device-side assert triggered`

I search the solution on the internet, some answers about the use of bce is useful for someone.
the answer is :  
https://stackoverflow.com/questions/60022388/pytorch-runtimeerror-reduce-failed-to-synchronize-cudaerrorassert-device-sid
But I have confirm the range of values to calculate bce loss. there is no problem.
So now I am confused.
I don't know how to solve this problem.

when I change the parameters to --binary_mask 0 and --loss l1
the model can go training.
so where the error can be found in my implementation?
Thank U.

**Comment by SheldonTsui** [comment]
@avis-ma Hello!
Under the binary mask mode, you can add an "assert" to ensure the values of gt masks are in {0,1} and the predicted masks are in the range [0,1]. This trick is very useful for your debug.

**Comment by avis-ma** [comment]
Thank you very much. I will retry this trick. 👍

**Comment by 813665269** [comment]
HI,
When I use the dataset you provide, the training of the model will terminate at the time of torch.utils.data.dataloader.You added the  sys.exit (- 1) command to the Musicmixdata function.When I deleted this command,I got this error:Sizes of tensors must match except in dimension 3.
I know this problem caused by the different dimension,but I don't know how to solve this problem.

**Comment by SheldonTsui** [comment]
@813665269 Please check whether you can load the frames and audio correctly. Debug in the "try" code part, and you will find the problems.

**Comment by 813665269** [comment]
hi,
I print the error data and try to delect all of them,but they are too many.They can run in the Sound-of-Pixels-master,but can not run in your project.I want to know how to Process the datasets to suit this project.
Show the error:
![VU8W}G$IUYP9D{Z1M)B5QS8](https://user-images.githubusercontent.com/70598441/94456316-1452ab00-01e6-11eb-81a4-9d200048c2b5.png)

**Comment by SheldonTsui** [comment]
@813665269 Hello, don't delete the "maybe" error data. Please **GO INTO** the code block to debug. Maybe there are some little differences in the data format. My data loader is largely based on "Sound-of-Pixels-master", but slightly different.
For example, you can manually load training data here:
https://github.com/SheldonTsui/Minus-Plus-Network/blob/7aa281b17f637a9f168aaf250039e560027a3817/main.py#L419
Add visualization code "for data in dataset_train: print(data.keys())", and you can go into such code block and find the exact bug.

**Comment by 813665269** [comment]
Thanks for your answer,
I print the datasets and get the construction of the wrong data and  correct data.In your project ,if the function cant read the data,it will return a tensor with all zeros.
![QQ图片20200929144840](https://user-images.githubusercontent.com/70598441/94522888-f24b3e00-0262-11eb-9aca-e0a4e218fffe.png)

**Comment by 813665269** [comment]
Hi,
I reshape the error data's tensor from [1,751,255] to [1,751,256] and then drop the command 'sys.exit(-2)' in MusicmixData .Now,this project can run.But I think the wrong tensor with all zeros must effect the model quality.
Can you give me some advice to treat it?
Thanks a lot.

**Comment by SheldonTsui** [comment]
@813665269 You should check why the error data happens. In other words, the normal shape of that tensor should be [1, 751, 256]. Why will such wrong tensors present in your case? To ensure all the training data is well-prepared is very important.
